# ACI playbook - Deploy new EPG and Contract
---

- name: Deploy new EPG and Contract
  hosts: apic
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password | default(omit) }}"
      private_key: "{{ aci_private_key | default(omit) }}"
      certificate_name: "{{ aci_certificate_name | default(omit) }}"
      validate_certs: "{{ aci_validate_certs }}"
      annotation: "orchestrator:ansible"
      state: present
      output_path: dryrun_data.json

  vars_files:
    - ./epg_con_vars.yaml

  tasks:
    - name: Add Tenant
      cisco.aci.aci_tenant:
        <<: *aci_login
        tenant: "{{ tenant_name }}"

    - name: Add BD {{ bd_name }}
      cisco.aci.aci_bd:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        bd: "{{ bd_name }}"
        vrf: "{{ vrf_name }}"
        l2_unknown_unicast: proxy
        arp_flooding: yes
        enable_routing: yes

    - name: Add subnets
      cisco.aci.aci_bd_subnet:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        bd: "{{ bd_name }}"
        gateway: "{{ subnet }}"
        mask: "{{ mask }}"
        scope: private

    - name: Add EPG "{{ epg_name }}"
      cisco.aci.aci_epg:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: "{{ epg_name }}"
        bd: "{{ bd_name }}"

    - name: Add domain binding to "{{ epg_name }}"
      cisco.aci.aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: "{{ epg_name }}"
        domain: PHY-USER
        domain_type: phys

    - name: Add contracts to "{{ epg_name }}"
      cisco.aci.aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: "{{ epg_name }}"
        contract: "{{ contract_name }}"
        contract_type: provider

    # Add contract to EPG-T2 and erroneously provider contract ALLOW-ALL
    - name: Add contracts to EPG-T2
      cisco.aci.aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: EPG-T2
        contract: "{{ contract_name }}"
        contract_type: consumer
  
    - name: Add contracts to EPG-T2
      cisco.aci.aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: EPG-T2
        contract: ALLOW-ALL
        contract_type: provider

    - name: Add contracts
      cisco.aci.aci_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ contract_name }}"
        scope: context

    - name: Add contract subjects
      cisco.aci.aci_contract_subject:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ contract_name }}"
        subject: S1
        reverse_filter: yes

    - name: Bind filters to contract subjects
      cisco.aci.aci_contract_subject_to_filter:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ contract_name }}"
        subject: S1
        filter: https

    # Contract Filters definition

    - name: Add filters
      cisco.aci.aci_filter:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        filter: https

    - name: Add filter entries
      cisco.aci.aci_filter_entry:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        filter: https
        entry: https
        ether_type: ip
        ip_protocol: tcp
        dst_port: 443
