dcmdr:
  children:
    apic:
      hosts:
        apic.swlab.bcn:
          ansible_host: apic.bcn
          aci_username: "admin"
          aci_password: "C1sc0123p"
          aci_validate_certs: no
