dcmdr:
  children:
    apic:
      hosts:
        apic-controller:
          ansible_host: '${{ secrets.APIC_HOST }}'
          aci_username: '${{ secrets.APIC_USERNAME }}'
          aci_password: '${{ secrets.APIC_PASSWORD }}'
          aci_validate_certs: no
