dcmdr:
  children:
    apic:
      hosts:
        apic.mdr1:
          ansible_host: apic1-mdr1.cisco.com
          aci_username: "admin"
          aci_password: "C!sco..123!!"
          aci_validate_certs: no
