dcmdr:
  children:
    apic:
      hosts:
        apic.mdr1:
          ansible_host: 10.50.3.111
          aci_username: "admin"
          aci_password: "C!sco..123!!"
          aci_validate_certs: no
